########################################################################################################################
#                                  Use this docker-compose file as a sample.                                           #
########################################################################################################################
services:
  app:
    image: thevickypedia/ytsync
    container_name: ytsync
    network_mode: bridge
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      # NOTE: Variables for docker context are case-sensitive
      # WORKDIR is set to /app in the Dockerfile, so the app's default "data" and "logs" will always work
      # LOGS_PATH and DATA_PATH are consumed only by docker context
      # The application only reads logs_dir and data_dir - this is a design choice for separation
      - ${LOGS_PATH:-./logs}:${logs_dir:-/app/logs}
      - ${DATA_PATH:-./data}:${data_dir:-/app/data}
      - ${DOWNLOAD_LOCATION:-./downloads}:${download_dir:-/app/downloads}
      - ~/.ssh/id_ed25519:/root/.ssh/id_ed25519:ro
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts:ro
    ports:
      # host_port:container_port
      - ${PORT:-4321}:${port:-4321}
    deploy:
      # 'reservations' key is supported only in swarm mode
      resources:
        limits:
          cpus: '1'
          memory: 200M
